services:

  product-service:

    build:
      context: .

    container_name: ecommerce-product-service

    ports:
      - "5002:5002"

    environment:
      PORT: 5002

      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: ecommerce_products

      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: development

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - default
      - ecommerce-network


  mysql:

    image: mysql:8.4

    container_name: ecommerce-product-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ecommerce_products

    ports:
      - "3308:3306"

    volumes:
      - product_mysql_data:/var/lib/mysql

      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-proot123"
        ]

      interval: 5s
      timeout: 5s
      retries: 10


volumes:

  product_mysql_data:


networks:

  ecommerce-network:
    external: true